import type { InquirySummary } from "./strapi/types";

export const fallbackQuotes: InquirySummary[] = [
  {
    documentId: "quote-ammonia-pending",
    inquiryType: "buyer",
    status: "pending",
    equipmentReferenceSnapshot: "PX-CP-NH3-1000",
    equipmentTitleSnapshot: "Complete Ammonia Plant 1000 MTPD - Haldor Topsoe",
    name: "Procurement Lead",
    company: "Saudi Aramco",
    email: "buyer@example.com",
    country: "Saudi Arabia",
    message: "Please send availability, inspection schedule, and relocation documents.",
    sourcePage: "/equipment/complete-ammonia-plant-1000-mtpd-haldor-topsoe",
    createdAt: "2026-06-21T12:40:07.000Z",
  },
  {
    documentId: "quote-crane-responded",
    inquiryType: "buyer",
    status: "responded",
    equipmentReferenceSnapshot: "PX-CR-18000",
    equipmentTitleSnapshot: "Manitowoc 18000 Ring Crane 2250t",
    name: "Heavy Lift Buyer",
    company: "Gulf Industrial Projects",
    email: "buyer@example.com",
    country: "United Arab Emirates",
    message: "Need configuration, lifting charts, and seller target terms.",
    sourcePage: "/equipment/manitowoc-18000-ring-crane-2250t",
    createdAt: "2026-06-20T09:15:00.000Z",
  },
  {
    documentId: "quote-compressor-negotiating",
    inquiryType: "buyer",
    status: "negotiating",
    equipmentReferenceSnapshot: "PX-OG-COMP-5000",
    equipmentTitleSnapshot: "Natural Gas Compressor 5000HP Ariel JGT/4",
    name: "Energy Buyer",
    company: "North American Midstream",
    email: "buyer@example.com",
    country: "United States",
    message: "Commercial terms under review after receiving maintenance file.",
    sourcePage: "/equipment/natural-gas-compressor-5000hp-ariel-jgt-4",
    createdAt: "2026-06-19T16:45:00.000Z",
  },
  {
    documentId: "quote-loader-accepted",
    inquiryType: "buyer",
    status: "accepted",
    equipmentReferenceSnapshot: "PX-LD-WA600",
    equipmentTitleSnapshot: "Komatsu WA600-8 Wheel Loader",
    name: "Mine Operator",
    company: "Chile Mining Operator",
    email: "buyer@example.com",
    country: "Chile",
    message: "Accepted after final inspection and transport quote.",
    sourcePage: "/equipment/komatsu-wa600-8-wheel-loader",
    createdAt: "2026-06-18T11:30:00.000Z",
  },
];
