import type { CategorySummary, EquipmentSummary, SiteSettings } from "./strapi/types";

export const fallbackCategories: CategorySummary[] = [
  {
    documentId: "fallback-chemical-plant",
    name: "Chemical Plant",
    slug: "chemical-plant",
    description: "Complete process plants and large industrial asset packages.",
    sortOrder: 10,
  },
  {
    documentId: "fallback-reactors",
    name: "Reactors",
    slug: "reactors",
    description: "Used glass-lined, stainless, and jacketed reactors.",
    sortOrder: 20,
  },
  {
    documentId: "fallback-mixers",
    name: "Mixers & Agitators",
    slug: "mixers-agitators",
    description: "Used process mixers, agitators, and blending systems.",
    sortOrder: 30,
  },
  {
    documentId: "fallback-tanks",
    name: "Tanks & Vessels",
    slug: "tanks-vessels",
    description: "Used tanks, pressure vessels, and process storage assets.",
    sortOrder: 40,
  },
  {
    documentId: "fallback-pumps",
    name: "Compressors & Pumps",
    slug: "pumps-compressors",
    description: "Used process pumps, compressors, and utility packages.",
    sortOrder: 50,
  },
  {
    documentId: "fallback-cranes",
    name: "Cranes",
    slug: "cranes",
    description: "Heavy lift cranes for plant relocation and industrial projects.",
    sortOrder: 60,
  },
  {
    documentId: "fallback-earthmoving",
    name: "Excavators & Loaders",
    slug: "earthmoving",
    description: "Construction and mining equipment for industrial sites.",
    sortOrder: 70,
  },
  {
    documentId: "fallback-oil-gas",
    name: "Oil & Gas",
    slug: "oil-gas",
    description: "Process, utility, and packaged assets for energy facilities.",
    sortOrder: 80,
  },
];

const image = (name: string, alt: string) => ({ url: `/images/${name}`, alternativeText: alt });

export const fallbackEquipment: EquipmentSummary[] = [
  {
    documentId: "fallback-liebherr-lr1350",
    title: "Liebherr LR 1350 Crawler Crane 350t",
    slug: "liebherr-lr-1350-crawler-crane-350t",
    reference: "PX-CR-1350",
    category: fallbackCategories[5],
    condition: "excellent",
    availability: "available",
    country: "Germany",
    location: "Hamburg, Germany",
    year: 2019,
    make: "Liebherr",
    model: "LR 1350",
    serialNumber: "LR1350-DE-2019",
    operatingHours: "4,200",
    weight: "350 t class",
    dimensions: "Crawler crane package",
    price: 2850000,
    currency: "USD",
    summary: "Heavy lift crawler crane suitable for petrochemical, refinery, and plant relocation work.",
    description:
      "Liebherr LR 1350 crawler crane in excellent operating condition. Full inspection package available by request, including maintenance files, lift configuration, and export logistics notes.",
    specifications: [
      { label: "Capacity", value: "350 t" },
      { label: "Boom", value: "Heavy lift configuration" },
      { label: "Serial number", value: "LR1350-DE-2019" },
      { label: "Operating hours", value: "4,200" },
      { label: "Weight", value: "350 t class" },
      { label: "Dimensions", value: "Crawler crane package" },
    ],
    features: [
      { text: "Inspection available in Germany" },
      { text: "Maintenance records available" },
      { text: "Export planning support" },
    ],
    mainImage: image("crane.png", "Liebherr crawler crane"),
    gallery: [image("petrochemical.png", "Petrochemical plant site")],
    sellerDisplayName: "European Heavy Lift Partner",
    isFeatured: true,
  },
  {
    documentId: "fallback-caterpillar-390f",
    title: "Caterpillar 390F Large Hydraulic Excavator",
    slug: "caterpillar-390f-large-hydraulic-excavator",
    reference: "PX-EX-390F",
    category: fallbackCategories[6],
    condition: "good",
    availability: "available",
    country: "United Kingdom",
    location: "Teesside, United Kingdom",
    year: 2018,
    make: "Caterpillar",
    model: "390F",
    serialNumber: "CAT390F-UK-2018",
    operatingHours: "8,700",
    weight: "90 t",
    dimensions: "Site transport configuration",
    price: 485000,
    currency: "USD",
    summary: "Large hydraulic excavator for industrial demolition, earthmoving, and plant site preparation.",
    description:
      "Caterpillar 390F with service history, suitable for heavy civil, quarry, and industrial plant projects. Buyer inspection and shipping coordination available.",
    specifications: [
      { label: "Operating weight", value: "90 t" },
      { label: "Serial number", value: "CAT390F-UK-2018" },
      { label: "Operating hours", value: "8,700" },
      { label: "Engine", value: "Cat diesel" },
      { label: "Dimensions", value: "Site transport configuration" },
    ],
    features: [{ text: "Good undercarriage" }, { text: "Inspection available" }],
    mainImage: image("excavator.png", "Caterpillar hydraulic excavator"),
    gallery: [image("dozer.png", "Heavy construction equipment")],
    sellerDisplayName: "UK Industrial Equipment Seller",
    isFeatured: true,
  },
  {
    documentId: "fallback-ammonia-plant",
    title: "Complete Ammonia Plant 1000 MTPD - Haldor Topsoe",
    slug: "complete-ammonia-plant-1000-mtpd-haldor-topsoe",
    reference: "PX-CP-NH3-1000",
    category: fallbackCategories[0],
    condition: "good",
    availability: "available",
    country: "Netherlands",
    location: "Rotterdam, Netherlands",
    year: 2008,
    make: "Haldor Topsoe",
    model: "Ammonia 1000 MTPD",
    serialNumber: "NH3-1000-NL",
    operatingHours: "N/A",
    weight: "Complete plant package",
    dimensions: "Plot plan available under NDA",
    currency: "USD",
    summary: "Complete ammonia plant package available for in-situ acquisition or relocation.",
    description:
      "Complete ammonia plant, 1000 MTPD capacity. Engineering documentation, operating manuals, and P&IDs are available to qualified buyers. Inspection available by appointment.",
    specifications: [
      { label: "Capacity", value: "1000 MTPD" },
      { label: "Technology", value: "Haldor Topsoe" },
      { label: "Serial number", value: "NH3-1000-NL" },
      { label: "Operating hours", value: "N/A" },
      { label: "Weight", value: "Complete plant package" },
      { label: "Dimensions", value: "Plot plan available under NDA" },
    ],
    features: [
      { text: "Engineering documents available" },
      { text: "Operating manuals available" },
      { text: "In-situ acquisition possible" },
    ],
    mainImage: image("chemical-plant.png", "Complete ammonia plant"),
    gallery: [image("petrochemical.png", "Petrochemical process plant")],
    sellerDisplayName: "International Process Plants",
    isFeatured: true,
  },
  {
    documentId: "fallback-manitowoc-18000",
    title: "Manitowoc 18000 Ring Crane 2250t",
    slug: "manitowoc-18000-ring-crane-2250t",
    reference: "PX-CR-18000",
    category: fallbackCategories[5],
    condition: "excellent",
    availability: "available",
    country: "United Arab Emirates",
    location: "Abu Dhabi, UAE",
    year: 2016,
    make: "Manitowoc",
    model: "18000 Ring Crane",
    serialNumber: "M18000-UAE-2016",
    operatingHours: "9,800",
    weight: "2250 t class",
    dimensions: "Ring crane package",
    price: 8500000,
    currency: "USD",
    summary: "High-capacity ring crane for refinery, offshore module, and heavy industrial lifting.",
    description:
      "Manitowoc 18000 ring crane package with documented operating history. Suitable for qualified heavy-lift buyers requiring large module handling capacity.",
    specifications: [
      { label: "Capacity", value: "2250 t" },
      { label: "Serial number", value: "M18000-UAE-2016" },
      { label: "Operating hours", value: "9,800" },
      { label: "Weight", value: "2250 t class" },
      { label: "Dimensions", value: "Ring crane package" },
    ],
    features: [{ text: "Heavy lift package" }, { text: "Export documentation review" }],
    mainImage: image("crane.png", "Manitowoc ring crane"),
    gallery: [image("oil-gas.png", "Oil and gas facility")],
    sellerDisplayName: "Middle East Lift Assets",
    isFeatured: true,
  },
  {
    documentId: "fallback-gas-compressor",
    title: "Natural Gas Compressor 5000HP Ariel JGT/4",
    slug: "natural-gas-compressor-5000hp-ariel-jgt-4",
    reference: "PX-OG-COMP-5000",
    category: fallbackCategories[7],
    condition: "good",
    availability: "available",
    country: "United States",
    location: "Texas, United States",
    year: 2014,
    make: "Ariel",
    model: "JGT/4",
    serialNumber: "ARL-JGT4-US-2014",
    operatingHours: "18,500",
    weight: "Packaged compressor skid",
    dimensions: "Skid drawings available",
    price: 1950000,
    currency: "USD",
    summary: "Natural gas compressor package for upstream or midstream service.",
    description:
      "5000HP Ariel JGT/4 natural gas compressor package with auxiliary systems. Maintenance file and skid drawings available to qualified buyers.",
    specifications: [
      { label: "Power", value: "5000 HP" },
      { label: "Type", value: "Natural gas compressor" },
      { label: "Serial number", value: "ARL-JGT4-US-2014" },
      { label: "Operating hours", value: "18,500" },
      { label: "Weight", value: "Packaged compressor skid" },
      { label: "Dimensions", value: "Skid drawings available" },
    ],
    features: [{ text: "Skid drawings available" }, { text: "Oil and gas application" }],
    mainImage: image("compressor.png", "Natural gas compressor package"),
    gallery: [image("oil-gas.png", "Oil and gas process equipment")],
    sellerDisplayName: "US Energy Equipment Group",
    isFeatured: true,
  },
  {
    documentId: "fallback-methanol-plant",
    title: "ICI Low-Pressure Methanol Plant 800,000 MT/YR",
    slug: "ici-low-pressure-methanol-plant-800000-mt-yr",
    reference: "PX-CP-MEOH-800",
    category: fallbackCategories[0],
    condition: "fair",
    availability: "available",
    country: "United States",
    location: "Louisiana, United States",
    year: 2001,
    make: "ICI / Johnson Matthey",
    model: "MeOH 800K MTPA",
    serialNumber: "ICI-MEOH-800-US",
    operatingHours: "N/A",
    weight: "Complete plant package",
    dimensions: "Plot plan available under NDA",
    currency: "USD",
    summary: "World-scale methanol plant available for in-situ acquisition or full relocation.",
    description:
      "ICI low-pressure methanol plant, 800,000 MT/yr world-scale capacity. Currently operational. Complete engineering documentation, operating manuals, and P&IDs available to qualified buyers.",
    specifications: [
      { label: "Capacity", value: "800,000 MT/YR" },
      { label: "Technology", value: "ICI / Johnson Matthey" },
      { label: "Serial number", value: "ICI-MEOH-800-US" },
      { label: "Operating hours", value: "N/A" },
      { label: "Weight", value: "Complete plant package" },
      { label: "Dimensions", value: "Plot plan available under NDA" },
    ],
    features: [{ text: "P&IDs available" }, { text: "Inspection by appointment" }],
    mainImage: image("chemical-plant.png", "Methanol plant"),
    gallery: [image("petrochemical.png", "Methanol and petrochemical facility")],
    sellerDisplayName: "International Process Plants",
    isFeatured: true,
  },
  {
    documentId: "fallback-reactor",
    title: "10,000 L Stainless Steel Jacketed Reactor",
    slug: "10000l-stainless-steel-jacketed-reactor",
    reference: "PX-R-001",
    category: fallbackCategories[1],
    condition: "good",
    availability: "available",
    country: "China",
    location: "Jiangsu, China",
    year: 2018,
    make: "Local Fabrication",
    model: "SS316L-JR-10000",
    serialNumber: "SSJR-10000-CN",
    operatingHours: "6,400",
    weight: "18 t",
    dimensions: "3.2 m dia x 6.8 m H",
    price: 68000,
    currency: "USD",
    summary: "Used stainless steel jacketed reactor for specialty chemical production.",
    description:
      "Used 10,000 L stainless steel jacketed reactor with top-entry agitator, manway, support legs, and heating/cooling jacket.",
    specifications: [
      { label: "Material", value: "SS316L contact parts" },
      { label: "Working volume", value: "10,000 L" },
      { label: "Drive", value: "22 kW" },
      { label: "Serial number", value: "SSJR-10000-CN" },
      { label: "Operating hours", value: "6,400" },
      { label: "Weight", value: "18 t" },
      { label: "Dimensions", value: "3.2 m dia x 6.8 m H" },
    ],
    features: [{ text: "Inspection available" }, { text: "Export packing support" }],
    mainImage: image("chemical-plant.png", "Chemical process plant equipment"),
    gallery: [image("petrochemical.png", "Petrochemical assets")],
    sellerDisplayName: "Verified industrial seller",
    isFeatured: false,
  },
  {
    documentId: "fallback-mixer",
    title: "High-Viscosity Mixer With Hydraulic Lifting",
    slug: "high-viscosity-mixer-hydraulic-lifting",
    reference: "PX-M-001",
    category: fallbackCategories[2],
    condition: "excellent",
    availability: "available",
    country: "China",
    location: "Zhejiang, China",
    year: 2021,
    make: "ProcessMix",
    model: "PM-HV-5000",
    serialNumber: "PMHV-5000-CN",
    operatingHours: "1,250",
    weight: "9 t",
    dimensions: "4.4 m L x 2.2 m W x 3.9 m H",
    price: 42000,
    currency: "USD",
    summary: "Used industrial mixer for coatings, adhesives, sealants, and viscous batches.",
    description:
      "Used high-viscosity mixer with hydraulic lifting frame and variable speed control.",
    specifications: [
      { label: "Batch capacity", value: "5,000 L" },
      { label: "Drive", value: "Variable speed" },
      { label: "Lift", value: "Hydraulic" },
      { label: "Serial number", value: "PMHV-5000-CN" },
      { label: "Operating hours", value: "1,250" },
      { label: "Weight", value: "9 t" },
      { label: "Dimensions", value: "4.4 m L x 2.2 m W x 3.9 m H" },
    ],
    features: [{ text: "Video inspection available" }, { text: "Short lead time" }],
    mainImage: image("drilling.png", "Industrial mixer and plant equipment"),
    gallery: [],
    sellerDisplayName: "Verified industrial seller",
    isFeatured: false,
  },
  {
    documentId: "fallback-loader",
    title: "Komatsu WA600-8 Wheel Loader",
    slug: "komatsu-wa600-8-wheel-loader",
    reference: "PX-LD-WA600",
    category: fallbackCategories[6],
    condition: "good",
    availability: "sold",
    country: "Chile",
    location: "Antofagasta, Chile",
    year: 2020,
    make: "Komatsu",
    model: "WA600-8",
    serialNumber: "KMT-WA600-CL",
    operatingHours: "6,100",
    weight: "55 t",
    dimensions: "Mining loader configuration",
    price: 650000,
    currency: "USD",
    summary: "Large wheel loader previously listed for mining and industrial materials handling.",
    description:
      "Komatsu WA600-8 wheel loader, sold after negotiation with a Chilean mining operator. Kept here as sample market activity and status tracking data.",
    specifications: [
      { label: "Serial number", value: "KMT-WA600-CL" },
      { label: "Operating hours", value: "6,100" },
      { label: "Weight", value: "55 t" },
      { label: "Dimensions", value: "Mining loader configuration" },
    ],
    features: [{ text: "Sold sample listing" }, { text: "Negotiation workflow example" }],
    mainImage: image("loader.png", "Komatsu wheel loader"),
    gallery: [],
    sellerDisplayName: "South America Mining Assets",
    isFeatured: false,
  },
];

export const fallbackSiteSettings: SiteSettings = {
  siteName: "PlantXchange",
  contactEmail: "sales@plantxchange.com",
  whatsappNumber: "+8613800000000",
  whatsappDisplayLabel: "WhatsApp",
  defaultSeoTitle: "PlantXchange | Used Industrial Process Equipment",
  defaultSeoDescription:
    "Source used tanks, reactors, mixers, pumps, compressors, and chemical plant assets through PlantXchange.",
  footerSummary:
    "The global B2B marketplace for buying and selling second-hand industrial equipment. Connecting serious buyers and sellers worldwide with confidence and transparency.",
};
